//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Leonardo/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Buri"",
            ""id"": ""d9473c2d-3223-45f1-a096-14dc1137b86b"",
            ""actions"": [
                {
                    ""name"": ""Movimento"",
                    ""type"": ""Value"",
                    ""id"": ""45662cb7-0637-4040-b84e-4a5921a8e668"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pular"",
                    ""type"": ""Button"",
                    ""id"": ""8aa5ce6c-9f59-443e-8cc4-9bf2845550f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetCameraAnalogico"",
                    ""type"": ""Value"",
                    ""id"": ""fee44496-399c-415a-89aa-b14b75e074e7"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UsarBaladeira"",
                    ""type"": ""Button"",
                    ""id"": ""01eb7908-3b59-4e54-8412-d71e58cc214a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EstaCorrendo"",
                    ""type"": ""Button"",
                    ""id"": ""2cfdb9c8-bda6-48a3-8a70-eab5424559c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UsarCanoa"",
                    ""type"": ""Button"",
                    ""id"": ""7ea33f02-dcdc-4633-969e-0f2993315165"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""5aa425b2-bc47-47e3-8992-62a8f1b60090"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventario"",
                    ""type"": ""Button"",
                    ""id"": ""fb723410-8744-491c-990e-b9bc8043d160"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SairMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6485191a-0235-4865-9ae0-d0d701245ed4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interagir"",
                    ""type"": ""Button"",
                    ""id"": ""cf45f25d-9559-4ecf-924b-05276755df0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Teclado WASD"",
                    ""id"": ""7a9763e3-9de9-452d-a6af-ea2421677ea0"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""3ceae747-479f-4957-bfd6-9f980db9e50c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""798d32e6-f688-46db-852b-d09fc27a6c5c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""caf0237a-15bf-417e-906f-70ff917a2b9f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""524d264e-1ab5-48a2-9a35-fdcaa0845ca2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""acb208e8-c514-40aa-b0d3-7737ca2d3cf2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""32170674-e787-4399-a2d4-79f0ab5e28a4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Teclado Setas"",
                    ""id"": ""8d0cdba4-919b-44e1-be88-be6374eebeba"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""f2938477-e308-43f1-9000-a98fd26a6d9a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""e8fba6bc-843a-4f24-8669-f11a6f8f473a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""e9e100ea-7dfb-4e66-849c-886daa0aa043"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""c33370b9-6dd5-4f81-b065-4dca35ebb9e8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""965d1d8a-8067-49c0-a5db-791071812d92"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""47ba1767-84a5-4754-9b3a-6fbd29baf164"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""7a2d7fac-9eae-4c3f-b77c-2d1532167a93"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""9c00b229-0969-490f-a7cd-048bc40d156c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""1010e613-bc25-4448-aa1f-513d83fcb8c1"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""7e3ef68f-d60e-4867-95fc-96eb16ae3c67"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""d26a9b07-1b21-49cf-afae-4b7c6fa873e0"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""1a32d560-e217-4fee-8e57-124882e94139"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""5b392a7d-f826-4688-88c3-0e5d7f98cb69"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Analogico"",
                    ""id"": ""28ce32ff-6c7d-47c5-b9c8-27d4cdb70fa3"",
                    ""path"": ""3DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""171a86c4-3736-4222-b5f2-2e722d084fd8"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""ab6961fd-bd83-4fe2-b71a-adce3f3f1d95"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""f70877e9-bd42-4deb-add0-df9725a1286b"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""e1776c00-367b-42a5-94db-a1eb9a1807fb"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""33c3c935-99e1-4d0b-9458-18493cd74ec3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""4741bdb6-806b-4cc9-a009-eab68915e8b9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""af0b7b77-4be2-488b-83b2-afeca6e7f984"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pular"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e092d93a-9f8c-49ad-9428-97138a943b84"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pular"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""1bee629f-15df-49b1-b6ea-3d4ba41817af"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetCameraAnalogico"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6cc69f2c-215e-48d4-ad91-f0ebb70f23ba"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetCameraAnalogico"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3da4952a-afd5-4134-b66e-01871d09bdfb"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetCameraAnalogico"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b0fc2a54-bc7f-4373-9537-cbbd93217513"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsarBaladeira"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba06a5e1-e139-434e-a2d1-223681e04cd8"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsarBaladeira"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0ee245d-f737-4004-a7f5-b47098cdeb09"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EstaCorrendo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbc81411-5f96-4913-a7c0-9d1a34b0158e"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EstaCorrendo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fecaf910-c7bb-4435-aa2b-f9744bc87703"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsarCanoa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""366acdb3-31c0-4c2b-a1e4-0937d9db0ed2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsarCanoa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b88923e8-0c56-4775-b5dc-adc562dbf512"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22391bdd-7652-4099-b2c3-35ce86dbc7fb"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab47849c-d8c1-49c0-885e-085fcd31b61a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29677210-ee1e-4648-b362-afa0c2843a0c"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventario"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e965ae7c-b589-42d6-8c1b-1cc26577a503"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventario"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1f2fe1e-9b61-4d7e-97ec-909a5b146af6"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventario"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace7ca48-57eb-4037-9348-f336768599a3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SairMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f3baf05-d24c-4d46-b454-d86cfc48d441"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SairMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de6d2b82-a015-4ef9-b63b-5fad76184f9f"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SairMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f6ed439-d124-43a3-bd45-c52bcb072415"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcacb4e0-e551-4e54-bfc7-fec863a295a3"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a612f53a-7eb5-4529-ae04-a63f7e34bce8"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Buri
        m_Buri = asset.FindActionMap("Buri", throwIfNotFound: true);
        m_Buri_Movimento = m_Buri.FindAction("Movimento", throwIfNotFound: true);
        m_Buri_Pular = m_Buri.FindAction("Pular", throwIfNotFound: true);
        m_Buri_SetCameraAnalogico = m_Buri.FindAction("SetCameraAnalogico", throwIfNotFound: true);
        m_Buri_UsarBaladeira = m_Buri.FindAction("UsarBaladeira", throwIfNotFound: true);
        m_Buri_EstaCorrendo = m_Buri.FindAction("EstaCorrendo", throwIfNotFound: true);
        m_Buri_UsarCanoa = m_Buri.FindAction("UsarCanoa", throwIfNotFound: true);
        m_Buri_Pause = m_Buri.FindAction("Pause", throwIfNotFound: true);
        m_Buri_Inventario = m_Buri.FindAction("Inventario", throwIfNotFound: true);
        m_Buri_SairMenu = m_Buri.FindAction("SairMenu", throwIfNotFound: true);
        m_Buri_Interagir = m_Buri.FindAction("Interagir", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Buri
    private readonly InputActionMap m_Buri;
    private List<IBuriActions> m_BuriActionsCallbackInterfaces = new List<IBuriActions>();
    private readonly InputAction m_Buri_Movimento;
    private readonly InputAction m_Buri_Pular;
    private readonly InputAction m_Buri_SetCameraAnalogico;
    private readonly InputAction m_Buri_UsarBaladeira;
    private readonly InputAction m_Buri_EstaCorrendo;
    private readonly InputAction m_Buri_UsarCanoa;
    private readonly InputAction m_Buri_Pause;
    private readonly InputAction m_Buri_Inventario;
    private readonly InputAction m_Buri_SairMenu;
    private readonly InputAction m_Buri_Interagir;
    public struct BuriActions
    {
        private @PlayerInputActions m_Wrapper;
        public BuriActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimento => m_Wrapper.m_Buri_Movimento;
        public InputAction @Pular => m_Wrapper.m_Buri_Pular;
        public InputAction @SetCameraAnalogico => m_Wrapper.m_Buri_SetCameraAnalogico;
        public InputAction @UsarBaladeira => m_Wrapper.m_Buri_UsarBaladeira;
        public InputAction @EstaCorrendo => m_Wrapper.m_Buri_EstaCorrendo;
        public InputAction @UsarCanoa => m_Wrapper.m_Buri_UsarCanoa;
        public InputAction @Pause => m_Wrapper.m_Buri_Pause;
        public InputAction @Inventario => m_Wrapper.m_Buri_Inventario;
        public InputAction @SairMenu => m_Wrapper.m_Buri_SairMenu;
        public InputAction @Interagir => m_Wrapper.m_Buri_Interagir;
        public InputActionMap Get() { return m_Wrapper.m_Buri; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuriActions set) { return set.Get(); }
        public void AddCallbacks(IBuriActions instance)
        {
            if (instance == null || m_Wrapper.m_BuriActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BuriActionsCallbackInterfaces.Add(instance);
            @Movimento.started += instance.OnMovimento;
            @Movimento.performed += instance.OnMovimento;
            @Movimento.canceled += instance.OnMovimento;
            @Pular.started += instance.OnPular;
            @Pular.performed += instance.OnPular;
            @Pular.canceled += instance.OnPular;
            @SetCameraAnalogico.started += instance.OnSetCameraAnalogico;
            @SetCameraAnalogico.performed += instance.OnSetCameraAnalogico;
            @SetCameraAnalogico.canceled += instance.OnSetCameraAnalogico;
            @UsarBaladeira.started += instance.OnUsarBaladeira;
            @UsarBaladeira.performed += instance.OnUsarBaladeira;
            @UsarBaladeira.canceled += instance.OnUsarBaladeira;
            @EstaCorrendo.started += instance.OnEstaCorrendo;
            @EstaCorrendo.performed += instance.OnEstaCorrendo;
            @EstaCorrendo.canceled += instance.OnEstaCorrendo;
            @UsarCanoa.started += instance.OnUsarCanoa;
            @UsarCanoa.performed += instance.OnUsarCanoa;
            @UsarCanoa.canceled += instance.OnUsarCanoa;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Inventario.started += instance.OnInventario;
            @Inventario.performed += instance.OnInventario;
            @Inventario.canceled += instance.OnInventario;
            @SairMenu.started += instance.OnSairMenu;
            @SairMenu.performed += instance.OnSairMenu;
            @SairMenu.canceled += instance.OnSairMenu;
            @Interagir.started += instance.OnInteragir;
            @Interagir.performed += instance.OnInteragir;
            @Interagir.canceled += instance.OnInteragir;
        }

        private void UnregisterCallbacks(IBuriActions instance)
        {
            @Movimento.started -= instance.OnMovimento;
            @Movimento.performed -= instance.OnMovimento;
            @Movimento.canceled -= instance.OnMovimento;
            @Pular.started -= instance.OnPular;
            @Pular.performed -= instance.OnPular;
            @Pular.canceled -= instance.OnPular;
            @SetCameraAnalogico.started -= instance.OnSetCameraAnalogico;
            @SetCameraAnalogico.performed -= instance.OnSetCameraAnalogico;
            @SetCameraAnalogico.canceled -= instance.OnSetCameraAnalogico;
            @UsarBaladeira.started -= instance.OnUsarBaladeira;
            @UsarBaladeira.performed -= instance.OnUsarBaladeira;
            @UsarBaladeira.canceled -= instance.OnUsarBaladeira;
            @EstaCorrendo.started -= instance.OnEstaCorrendo;
            @EstaCorrendo.performed -= instance.OnEstaCorrendo;
            @EstaCorrendo.canceled -= instance.OnEstaCorrendo;
            @UsarCanoa.started -= instance.OnUsarCanoa;
            @UsarCanoa.performed -= instance.OnUsarCanoa;
            @UsarCanoa.canceled -= instance.OnUsarCanoa;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Inventario.started -= instance.OnInventario;
            @Inventario.performed -= instance.OnInventario;
            @Inventario.canceled -= instance.OnInventario;
            @SairMenu.started -= instance.OnSairMenu;
            @SairMenu.performed -= instance.OnSairMenu;
            @SairMenu.canceled -= instance.OnSairMenu;
            @Interagir.started -= instance.OnInteragir;
            @Interagir.performed -= instance.OnInteragir;
            @Interagir.canceled -= instance.OnInteragir;
        }

        public void RemoveCallbacks(IBuriActions instance)
        {
            if (m_Wrapper.m_BuriActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBuriActions instance)
        {
            foreach (var item in m_Wrapper.m_BuriActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BuriActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BuriActions @Buri => new BuriActions(this);
    public interface IBuriActions
    {
        void OnMovimento(InputAction.CallbackContext context);
        void OnPular(InputAction.CallbackContext context);
        void OnSetCameraAnalogico(InputAction.CallbackContext context);
        void OnUsarBaladeira(InputAction.CallbackContext context);
        void OnEstaCorrendo(InputAction.CallbackContext context);
        void OnUsarCanoa(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnInventario(InputAction.CallbackContext context);
        void OnSairMenu(InputAction.CallbackContext context);
        void OnInteragir(InputAction.CallbackContext context);
    }
}
